version: '3.8'

services:
  springboot-app:
    build:
      context: ./shopify-sevdesk-integration-backend
      dockerfile: /Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - db

  angular-app:
    build:
      context: ./sevdesk-shopify-integration
      dockerfile: ./dockerfile
    ports:
      - "4200:80"
    networks:
      - app-network

  db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
