version: '3.8'

services:
  springboot-app:
    restart: always
    build:
      dockerfile: ./shopify-sevdesk-integration-backend/Dockerfile
    networks:
      - app-network
    depends_on:
      mysqldb:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/mydatabase
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password

  mysqldb:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=mydatabase
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      retries: 10
      interval: 3s
      timeout: 30s

  angular-app:
    build:
      args:
        progress: plain
      context: .
      dockerfile: ./shopify-sevdesk-intgeration-frontend/Dockerfile
    ports:
      - "80:80"
    networks:
      - app-network

  keycloak:
    image: keycloak/keycloak:latest
    ports:
      - "8080:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=password
    command: start-dev
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    name: app-network

volumes:
  db-data:



