version: '3.8'

services:
  springboot-app:
    build:
      dockerfile: ./shopify-sevdesk-integration-backend/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - db

  nginx:
    image: nginx:stable-alpine
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - springboot-app
    networks:
      - app-network

  db:
    platform: linux/amd64
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

  angular-app:
    build:
      dockerfile: ./sevdesk-shopify-integration/Dockerfile
    ports:
      - "4200:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:


