# Stage 1: Install dependencies
FROM node:18 AS install
WORKDIR /app
COPY package.json ./
COPY package-lock.json ./
RUN npm install

# Stage 2: Build the Angular application
FROM install as build
COPY . .
RUN npx nx reset && npx nx build shopify-sevdesk

FROM nginx:stable-alpine
WORKDIR /usr/share/nginx/html
RUN rm -rf ./*
COPY --from=build /app/dist/apps/shopify-sevdesk ./
COPY nginx.conf /etc/nginx/conf.d/default.conf
ENTRYPOINT ["nginx", "-g", "daemon off;"]
