# Stage 1: Build the Angular application
FROM node:18 AS install
WORKDIR /app
COPY package.json ./
COPY package-lock.json ./
RUN npm install

FROM install as build
COPY apps ./
RUN npx nx build shopify-sevdesk --prod \
FROM nginx:stable-alpine
WORKDIR /usr/share/nginx/html
RUN rm -rf ./*
COPY --from=build /app/dist/apps/shopify-sevdesk ./ \
RUN sed -i '10i \ttry_files $uri $uri/ /index.html;' /etc/nginx/conf.d/default.confENTRYPOINT ["nginx", "-g", "daemon off;"]



